#1256 Clarify sound when switching from feed to monitoring
opfab/operatorfabric-core pull request #1406
Opened 2021-07-07 15:19 UTC by quinarygio

Fix #1256 

Release notes

In Bugs section:
#1256 : Clarify sound when switching from feed to monitoring

Signed-off-by: Giovanni Ferrari <giovanni.ferrari@soft.it>

2021-07-09 07:43 UTC, freddidierRTE commented
The difference between Filter and SearchFilter is not clear , we should find another way to distinguish thinks 

This solution is always filtering in background even if do not have the monitoring screen available or used , when having a lot of cards it may created unnecessary overload

Solution proposed : create these filters in the monitoring component and name the effects in ngrx with monitoring in the names

2021-07-09 07:43 UTC, freddidierRTE requested changes

2021-07-09 07:43 UTC, freddidierRTE commented on ui/main/src/app/services/lightcards.service.ts
> +    }
We do not need to sort the card for the monitoring filter ?

2021-07-13 10:01 UTC, AlexGuironnetRTE approved these changes
Code refactoring OK
Manual tests OK:
- No changes to sound notification behaviour for feed screen
- For monitoring screen, sounds are played based on feed filters only, the Service, Process, and Process Status filters present on the Monitoring screen are not taken into account. One notable exception is the business period, which is the one selected for the monitoring screen (using the timeline buttons) and which is not synced with the one for the feed. This is not in the scope of this issue, but I'm not sure if it's an optimal user experience so I created #1441 to discuss it.

2021-07-13 10:02 UTC, merged