#1270 Synchronize JWT data with database
opfab/operatorfabric-core pull request #1449
Opened 2021-07-15 07:12 UTC by quinarygio

Fix #1270 

Release notes

In Tasks section:
#1270 Synchronize JWT token data with database

Signed-off-by: Giovanni Ferrari <giovanni.ferrari@soft.it>

2021-07-20 07:57 UTC, freddidierRTE commented
- In UserController , the method : `public User updateUser(HttpServletRequest request, HttpServletResponse response, String login, User user) throws Exception {`  may be removed as it is only used by the front to create user

2021-08-13 14:48 UTC, quinarygio commented
> * In UserController , the method : `public User updateUser(HttpServletRequest request, HttpServletResponse response, String login, User user) throws Exception {`  may be removed as it is only used by the front to create user

    Maybe it would be better to keep separated methods for creating and updating a user, to be more consistent with REST verbs and to avoid the creation of wrong users when trying to update a user passing a wrong username by mistake.

2021-09-06 12:41 UTC, freddidierRTE requested changes

2021-09-06 12:41 UTC, freddidierRTE commented on services/core/users/src/main/java/org/opfab/users/controllers/UsersController.java
> +                updatedFromToken = !new HashSet<String>(existingUser.getEntities()).equals(new HashSet<String>(user.getGroups()));
it shall be :  
updatedFromToken = !new HashSet<String>(existingUser.getEntities()).equals(new HashSet<String>(user.**getEntities())**); ?

2021-09-07 11:03 UTC, merged