Use user perimeter to present process/state list in UI (#1908)
opfab/operatorfabric-core pull request #1980
Opened 2021-10-26 17:44 UTC by vlo-rte

Release notes : 

In Features section : 

#1908 : Use user perimeter to present process/state list in UI

2021-11-03 17:09 UTC, quinarygio commented
Should add unit tests for lists construction as required in the issue?

2021-11-03 17:09 UTC, quinarygio requested changes

2021-11-04 09:19 UTC, vlo-rte commented on ui/main/src/app/services/process-states-dropdown-list.service.ts
> +/* Copyright (c) 2018-2021, RTE (http://www.rte-france.com)
> Should add unit tests for lists construction as required in the issue?

As discussed with Giovanni and the team, writing unit tests for this functionality can be complicated so we decided to merge and to write tests later, an issue has been created : #2015
Maybe this functionality can be tested with cypress tests , testing the items of the dropdownlist ?
To be discussed

2021-11-04 09:28 UTC, vlo-rte commented on ui/main/src/app/services/process-states-dropdown-list.service.ts
> +/* Copyright (c) 2018-2021, RTE (http://www.rte-france.com)
> should be only 2021 ?

You're right. I made an update.

2021-11-04 09:29 UTC, quinarygio approved these changes

2021-11-04 10:10 UTC, merged