Add a spinner when loading logging cards (#1991)
opfab/operatorfabric-core pull request #2019
Opened 2021-11-04 14:52 UTC by olivierPigeon-RTE

2021-11-04 16:16 UTC, olivierPigeon-RTE commented
Duplicated lines are not new to this pr and were already existing, so this commit did not add duplicated code

2021-11-04 17:16 UTC, vlo-rte requested changes
When there are already cards displayed, we can see this : 
![image](https://user-images.githubusercontent.com/57365872/140387386-88cf4ccb-5f4f-4928-b97e-a2d1964ef7f3.png)

I suppose this is not the wanted behaviour ?

2021-11-15 10:18 UTC, vlo-rte requested changes
The problem is not solved because when there are already displayed results, the spinner doesn't appear anymore although it takes more than 1 second. Can you correct it please ?

2021-11-30 15:26 UTC, vlo-rte approved these changes

2021-11-30 15:27 UTC, merged