User virtualselect for mutliselect in templates and in opfab code (#2868)
opfab/operatorfabric-core pull request #3062
Opened 2022-05-25 15:45 UTC by freddidierRTE

- In release note :
  -  In chapter :  Tasks
  -  Text : #2868 Use Virtual Select component (https://sa-si-dev.github.io/virtual-select/#/) for multiselect

2022-05-26 13:02 UTC, quinarygio reviewed
Tests ok, style ok

2022-05-30 08:30 UTC, freddidierRTE commented on ui/main/package.json
> +    "virtual-select-plugin": "^1.0.29",
done

2022-05-30 08:31 UTC, freddidierRTE commented on ui/main/src/app/modules/admin/components/editmodal/entities/edit-entity-modal.component.ts
> +    //this.parents.setValue(this.parents.value.map(entity => entity.id));
done

2022-05-30 08:31 UTC, freddidierRTE commented on ui/main/src/app/modules/externaldevicesconfiguration/editModal/externaldevicesconfiguration-modal.component.ts
> +    console.log("this.externalDeviceIds.value=",this.externalDeviceIds.value);
done

2022-05-30 08:31 UTC, freddidierRTE commented on ui/main/src/app/modules/share/archives-logging-filters/archives-logging-filters.component.ts
> +        console.log("Process group filter:",ids );
done

2022-05-30 14:07 UTC, quinarygio commented
There is a difference respect to the previous component when using the select all checkbox after filtering values:  
Filter values using Search option -> click "select all" checkbox -> all the filtered values are selected but the "select all" checkbox" is unchecked and is not possible to unselect all the filtered values.

2022-05-30 14:08 UTC, quinarygio requested changes

2022-05-30 16:07 UTC, freddidierRTE commented
> There is a difference respect to the previous component when using the select all checkbox after filtering values: Filter values using Search option -> click "select all" checkbox -> all the filtered values are selected but the "select all" checkbox" is unchecked and is not possible to unselect all the filtered values.

An issue has been post on the topic : https://github.com/sa-si-dev/virtual-select/issues/151

2022-05-30 16:13 UTC, freddidierRTE commented on ui/main/src/app/modules/archives/archives.module.ts
>      DatetimeFilterModule,
done

2022-05-30 16:13 UTC, freddidierRTE commented on ui/main/src/app/modules/monitoring/monitoring.module.ts
> +        , TimelineButtonsModule, AgGridModule
Done

2022-05-30 16:14 UTC, freddidierRTE commented on ui/main/src/app/services/processes.service.ts
> +    public getProcessesPerProcessGroupsNew(processesFilter?: string[]): Map<any, any> {
done

2022-05-31 08:46 UTC, quinarygio approved these changes

2022-05-31 08:46 UTC, merged