Add cypress tests for OpFab started in another tab (#3103)
opfab/operatorfabric-core pull request #3119
Opened 2022-06-09 08:50 UTC by olivierPigeon-RTE

Signed-off-by: olivierPigeon-RTE <olivier.pigeon@rte-france.com>

Nothing in release notes

2022-06-10 05:16 UTC, freddidierRTE requested changes

2022-06-10 05:16 UTC, freddidierRTE commented on src/test/cypress/cypress/integration/CheckIfOpfabUrlIsAlreadyTaken.spec.js
> +* */
Remove comment not related to these tests

2022-06-10 05:16 UTC, freddidierRTE commented on src/test/cypress/cypress/integration/CheckIfOpfabUrlIsAlreadyTaken.spec.js
> +
Change describe text to reflect the current tests

2022-06-10 05:16 UTC, freddidierRTE commented on src/test/cypress/cypress/integration/CheckIfOpfabUrlIsAlreadyTaken.spec.js
> +/* Copyright (c) 2021-2022, RTE (http://www.rte-france.com)
Copyright is only 2022

2022-06-16 07:37 UTC, olivierPigeon-RTE commented on src/test/cypress/cypress/integration/CheckIfOpfabUrlIsAlreadyTaken.spec.js
> +/* Copyright (c) 2021-2022, RTE (http://www.rte-france.com)
done

2022-06-16 11:38 UTC, merged