Creation of a spinner component (#3163)
opfab/operatorfabric-core pull request #3239
Opened 2022-06-29 12:42 UTC by olivierPigeon-RTE

Signed-off-by: olivierPigeon-RTE <olivier.pigeon@rte-france.com>

- In release note :
  -  In chapter :  Features Bugs Tasks
  -  Text : #xxx ...

2022-06-29 16:24 UTC, olivierPigeon-RTE commented on ui/main/src/app/modules/share/spinner/spinner.component.html
> +       {{ getTranslation(loadingText) }}
it is actually needed, {{loadingText}} doesn't display the text properly

2022-07-01 11:51 UTC, freddidierRTE requested changes

2022-07-01 11:51 UTC, freddidierRTE commented on ui/main/src/app/modules/archives/archives.component.html
> +<of-spinner *ngIf="loadingInProgress" loadingText="archive.loadingInProgress"></of-spinner>
use the generic message here and remove translation key archive.loadingInProgress

2022-07-01 11:51 UTC, freddidierRTE commented on ui/main/src/app/modules/share/spinner/spinner.component.ts
> +    }
not needed anymore

2022-07-01 11:51 UTC, freddidierRTE commented on ui/main/src/app/modules/share/spinner/spinner.module.ts
> +    imports: [CommonModule, TranslateModule, NgbModule],
Translate module shall not be needed anymore due to previous review comment

2022-07-01 11:51 UTC, freddidierRTE commented on ui/main/src/app/modules/realtimeusers/realtimeusers.component.ts
> +    @ViewChild('spinner') customSpinner: SpinnerComponent;
I do not see any use of it ?

2022-07-01 11:51 UTC, freddidierRTE commented
rebase is needed to solve conflict

2022-07-01 12:11 UTC, freddidierRTE requested changes

2022-07-01 12:11 UTC, freddidierRTE commented on src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js
>      before('Set up configuration', function () {
Add this two method in cypress command.js to avoid duplication

2022-07-01 13:32 UTC, freddidierRTE commented on ui/main/src/app/modules/share/spinner/spinner.module.ts
> +    imports: [CommonModule, TranslateModule, NgbModule],
yes you are right

2022-07-01 15:06 UTC, freddidierRTE requested changes

2022-07-01 15:06 UTC, freddidierRTE commented on src/test/cypress/cypress/integration/1-RealTimeUsers.spec.js
> +        // We move to logging screen
remove invalid comment

2022-07-01 15:06 UTC, freddidierRTE commented on src/test/cypress/cypress/integration/ActivityArea.spec.js
> +        // We move to logging screen
remove invalid comment

2022-07-01 15:06 UTC, freddidierRTE commented on ui/main/src/app/modules/share/spinner/spinner.component.ts
> +    constructor(protected translate: TranslateService) {}
translate service not needed here

2022-07-04 06:54 UTC, merged