Add the possibility to disable an external device (#3298)
opfab/operatorfabric-core pull request #3400
Opened 2022-07-22 15:53 UTC by olivierPigeon-RTE

- In release note :
  -  In chapter :  Features
  -  Text : #3298 : Add the possibility to disable an external device

2022-07-26 15:52 UTC, freddidierRTE commented
1) When a device is disable it is still possible to send signal to the external device :

Start opfab (docker mode)
Disconnect CDS-1 via admin 
Go to operator 1 set sound to external devices via settings 
Send cards 
Go to the dummy modbus devices logs (docker logs -f dummy-modbus-device_1) 
You see that it receive the signal for the card 

Correct the problem and add karate test to verify it is corrected 

2) Design of the external devices configuration page shall be equivalent to the admin one : 
 - margin or padding left / right
 - no title on top the table  (EXTERNAL DEVICES CONFIGURATION to remove)


3) Translate columns title for devices screen

4) Invert button position : first devices and then users  

5) Change button titles:
	- Devices --> External Devices  
	- User --> User Configuration 
(to do for all languages)

2022-07-26 15:53 UTC, freddidierRTE requested changes

2022-07-27 09:14 UTC, olivierPigeon-RTE commented on ui/main/src/app/modules/admin/components/cell-renderers/checkbox-cell-renderer.component.ts
> +    }
it is necessary to implement the class ICellRendererAngularComp

2022-07-27 11:52 UTC, olivierPigeon-RTE commented on services/external-devices/src/test/java/org/opfab/externaldevices/services/DevicesServiceShould.java
> +
I agree, the name of this method is not great

I tried to add mock definitions in the @BeforeAll and BeforeEach in order not to call these methods in the tests themselves. It turns out :
* @BeforeAll method needs to be static and therefore cannot update non static fields
* if I add the mock definitions in the BeforeEach, every test that does not need all the mocks defined fail with this error
  

> Unnecessary stubbings detected.
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):

2022-07-29 14:23 UTC, merged