Add export feature for admin screens (#3503)
opfab/operatorfabric-core pull request #3507
Opened 2022-09-02 13:23 UTC by quinarygio

Fix #3503

Signed-off-by: Giovanni Ferrari <giovanni.ferrari@soft.it>

- In release note :
  -  In chapter :  Features
  -  Text : #3503 : Add export feature for admin screens

2022-09-05 15:33 UTC, vlo-rte commented
Translation for titles of the columns in the export file is not taken into account. For example in french language, we have : 
![image](https://user-images.githubusercontent.com/57365872/188482340-1a0b0faa-407b-49ac-a0fa-aa36dbf69c02.png)

2022-09-05 15:34 UTC, vlo-rte commented
I think we should display group name and entity name instead of ids, the same than what we display on the screen. Currently we have : 
![image](https://user-images.githubusercontent.com/57365872/188482487-2bf1e273-dd3a-42e2-a3a7-fb15c7b1bc98.png)

2022-09-05 15:47 UTC, vlo-rte commented
For groups sheet : I think we should display YES/NO (etc...) instead of 1/0 for the column "realtime". I think we should also display the perimeters in alphabetical order (like it seems to be the case on the screen).
![image](https://user-images.githubusercontent.com/57365872/188483578-5b92bf6d-bf56-4495-ae2f-7684a11f9e55.png)

2022-09-05 16:09 UTC, vlo-rte commented
For perimeters sheet : I thinhk we should display the state name instead of its id. Currently we have : 
![image](https://user-images.githubusercontent.com/57365872/188487165-4550d73e-5f5b-45f5-a59d-7df0d9e8c85f.png)

2022-09-05 16:38 UTC, vlo-rte requested changes
Please see my comments.

2022-09-14 06:40 UTC, freddidierRTE commented on ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
> +            const celRenderer = new this.gridOptions.components[renderer].prototype.constructor();
cellRender instead of celRender

2022-09-14 06:40 UTC, freddidierRTE commented on ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
> +    private getExportHeader(header: string): string {
suggestion : this.getTranslatedHeaderName(header: string)

2022-09-14 06:40 UTC, freddidierRTE commented on ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
> +    private getMappedName(id: string, renderer: string): string {
getNameFromId

2022-09-15 08:01 UTC, merged