Remove @Autowired (#3926)
opfab/operatorfabric-core pull request #3935
Opened 2022-12-13 11:55 UTC by freddidierRTE

Nothing in release note

2022-12-15 15:16 UTC, quinarygio requested changes

2022-12-15 15:16 UTC, quinarygio commented on services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/RabbitMQEntryPoint.java
>              FanoutExchange processExchange,
Fix Copyright

2022-12-15 15:16 UTC, quinarygio commented on services/cards-publication/src/test/java/org/opfab/cards/publication/configuration/TestCardReceiver.java
Fix Copyright

2022-12-15 15:16 UTC, quinarygio commented on services/external-devices/src/test/java/org/opfab/externaldevices/drivers/ModbusDriverFactoryShould.java
> +        assertThrows(ExternalDeviceDriverException.class, () -> {modbusDriverFactory.create("unresolvable Host",123);});
Fix Copyright

2022-12-15 15:16 UTC, quinarygio commented on services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityChecks.java
>  @Slf4j
Fix Copyright

2022-12-15 15:16 UTC, quinarygio commented on tools/spring/spring-mongo-utilities/src/main/java/org/opfab/springtools/configuration/mongo/MongoConfiguration.java
Fix Copyright

2022-12-15 15:16 UTC, quinarygio commented on tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/I18nProcessesCache.java
Fix Copyright

2022-12-15 15:16 UTC, quinarygio commented on tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OAuth2GenericConfiguration.java
>  import org.springframework.context.annotation.Bean;
Fix Copyright

2022-12-15 15:16 UTC, quinarygio commented on tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OAuth2ReactiveConfiguration.java
Fix Copyright

2022-12-15 15:16 UTC, quinarygio commented on tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/jwt/groups/GroupsUtils.java
>  import java.util.stream.Collectors;
Fix Copyright

2022-12-20 14:07 UTC, freddidierRTE commented on services/cards-consultation/src/main/java/org/opfab/cards/consultation/services/RabbitMQEntryPoint.java
>              FanoutExchange processExchange,
Fixed

2022-12-20 14:07 UTC, freddidierRTE commented on services/cards-publication/src/test/java/org/opfab/cards/publication/configuration/TestCardReceiver.java
Fixed

2022-12-20 14:07 UTC, freddidierRTE commented on services/external-devices/src/test/java/org/opfab/externaldevices/drivers/ModbusDriverFactoryShould.java
> +        assertThrows(ExternalDeviceDriverException.class, () -> {modbusDriverFactory.create("unresolvable Host",123);});
Fixed

2022-12-20 14:07 UTC, freddidierRTE commented on services/users/src/main/java/org/opfab/users/configuration/oauth2/WebSecurityChecks.java
>  @Slf4j
Fixed

2022-12-20 14:07 UTC, freddidierRTE commented on tools/spring/spring-mongo-utilities/src/main/java/org/opfab/springtools/configuration/mongo/MongoConfiguration.java
Fixed

2022-12-20 14:07 UTC, freddidierRTE commented on tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/I18nProcessesCache.java
Fixed

2022-12-20 14:07 UTC, freddidierRTE commented on tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/OAuth2ReactiveConfiguration.java
Fixed

2022-12-20 14:07 UTC, freddidierRTE commented on tools/spring/spring-oauth2-utilities/src/main/java/org/opfab/springtools/configuration/oauth/jwt/groups/GroupsUtils.java
>  import java.util.stream.Collectors;
Fixed

2022-12-20 16:55 UTC, merged