Add new field "entityRecipientsForInformation" (#4153)
opfab/operatorfabric-core pull request #4196
Opened 2023-02-08 13:43 UTC by vlo-rte

Signed-off-by: vlo-rte <valerie.longa@rte-france.com>

- In release note :
  -  In chapter :  Features Bugs Tasks
  -  Text : #xxx ...

2023-02-23 12:52 UTC, freddidierRTE commented
If there is only recipient for information  , the acknowledged word shall not be visible
![image](https://user-images.githubusercontent.com/58251627/220909992-4bc03df5-9590-469c-be7a-130bff0b4ef5.png)

2023-02-23 12:56 UTC, freddidierRTE requested changes

2023-02-23 12:56 UTC, freddidierRTE commented on services/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCardData.java
> +    private List<Recipient> recipientForInformationList;
not needed

2023-02-23 12:56 UTC, freddidierRTE commented on services/businessconfig/src/main/modeling/swagger.yaml
> +          $ref: '#/definitions/Recipient'
not needed

2023-02-23 12:56 UTC, freddidierRTE commented on services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardOperationData.java
> +
not needed

2023-02-23 13:04 UTC, freddidierRTE commented
Add documentation for method  usercardTemplateGateway.getSelectedEntityRecipientsForInformation

like in https://opfab.github.io/documentation/current/reference_doc/#_get_selected_recipient_entities_list

2023-02-23 13:06 UTC, vlo-rte commented on services/cards-consultation/src/main/java/org/opfab/cards/consultation/model/LightCardConsultationData.java
> +            builder.entityRecipientsForInformation(other.getEntityRecipientsForInformation());
Done.

2023-02-23 13:06 UTC, vlo-rte commented on services/cards-publication/src/main/java/org/opfab/cards/publication/model/ArchivedCardPublicationData.java
> +    @Indexed
Done.

2023-02-23 13:08 UTC, vlo-rte commented on services/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCardData.java
> +    private List<Recipient> recipientForInformationList;
Done.

2023-02-23 13:09 UTC, vlo-rte commented on services/businessconfig/src/main/modeling/swagger.yaml
> +          $ref: '#/definitions/Recipient'
Done.

2023-02-23 13:09 UTC, vlo-rte commented on services/cards-publication/src/main/java/org/opfab/cards/publication/model/CardOperationData.java
> +
Done.

2023-02-23 13:11 UTC, vlo-rte commented on services/cards-publication/src/main/modeling/swagger.yaml
> +          and not in 'entityRecipients'.
Done.

2023-02-23 13:12 UTC, vlo-rte commented on services/cards-publication/src/main/modeling/swagger.yaml
> +          and not in 'entityRecipients'.
Done.

2023-02-23 13:13 UTC, vlo-rte commented on services/cards-publication/src/main/java/org/opfab/cards/publication/services/CardNotificationService.java
> +
Done.

2023-02-23 13:35 UTC, vlo-rte commented
> If there is only recipient for information , the acknowledged word shall not be visible ![image](https://user-images.githubusercontent.com/58251627/220909992-4bc03df5-9590-469c-be7a-130bff0b4ef5.png)

Done.

2023-02-23 13:40 UTC, vlo-rte commented
> Add documentation for method usercardTemplateGateway.getSelectedEntityRecipientsForInformation
> 
> like in https://opfab.github.io/documentation/current/reference_doc/#_get_selected_recipient_entities_list

Done.

2023-02-24 14:13 UTC, merged

2023-02-24 14:16 UTC, vlo-rte commented
I've merged my pull request because the review has been done and now the builds are successful.