Use operating system notifications (#3778)
opfab/operatorfabric-core pull request #4294
Opened 2023-03-08 10:57 UTC by lhazenoot

- In release note :
  -  In chapter :  Features
  -  Text : #3778

2023-03-08 11:01 UTC, lhazenoot commented
@freddidierRTE 
To receive notifications, you need to manually allow notifications in the settings of your browser. There is no easy way to do this trough opfab.

2023-03-13 10:17 UTC, freddidierRTE commented
it does not build

2023-03-13 15:15 UTC, freddidierRTE requested changes

2023-03-13 15:15 UTC, freddidierRTE commented on ui/main/src/app/business/services/system-notification.service.ts
> +        if (window['Cypress']) window['systemNotificationService'] = this;
We are not gonna test this service yet with cypress , so you can remove this line

2023-03-13 15:15 UTC, freddidierRTE commented on ui/main/src/assets/i18n/en.json
> +    "notificationOnOperatingSystem": "NOTIFICATIONS FOR CARDS WITH SEVERITY",
SYSTEM NOTIFICATION

2023-03-13 15:15 UTC, freddidierRTE commented on ui/main/src/assets/i18n/fr.json
> +    "notificationOnOperatingSystem": "NOTIFICATIONS POUR LES CARTES DE TYPE",
NOTIFICATIONS SYSTEM POUR ...

2023-03-20 07:06 UTC, merged