Scrollable list in the geomap popup (#4344)
opfab/operatorfabric-core pull request #4357
Opened 2023-03-27 08:11 UTC by lhazenoot

- In release note :
  -  In chapter :  Features
  -  Text : #4344

2023-03-28 10:24 UTC, quinarygio requested changes

2023-03-28 10:24 UTC, quinarygio commented on ui/main/src/app/modules/feed/components/map/map.component.scss
>      border-radius: 10px;
Could you just fix the copyright header:  Copyright (c) 2022-**2023**, Alliander

2023-03-28 10:57 UTC, quinarygio commented
In firefox cards title goes on newline : 
![image](https://user-images.githubusercontent.com/19426449/228214908-f7146aa5-1267-446c-bb3d-ec35ed6d1bcf.png)

2023-03-28 12:30 UTC, lhazenoot commented
> In firefox cards title goes on newline : ![image](https://user-images.githubusercontent.com/19426449/228214908-f7146aa5-1267-446c-bb3d-ec35ed6d1bcf.png)

@quinarygio Hmm, that is weird! At mine, it just looks normal in firefox. Don't know if this is really a problem? Or can we just leave it for what it is?

<img width="369" alt="Firefox geomap popup" src="https://user-images.githubusercontent.com/91895080/228235618-65e1beba-e207-4920-ae05-d8266f975494.png">

2023-03-28 13:15 UTC, quinarygio commented
> > In firefox cards title goes on newline : ![image](https://user-images.githubusercontent.com/19426449/228214908-f7146aa5-1267-446c-bb3d-ec35ed6d1bcf.png)
> 
> @quinarygio Hmm, that is weird! At mine, it just looks normal in firefox. Don't know if this is really a problem? Or can we just leave it for what it is?
> 
> <img alt="Firefox geomap popup" width="369" src="https://user-images.githubusercontent.com/91895080/228235618-65e1beba-e207-4920-ae05-d8266f975494.png">

The issue occurs only when there is the scrollbar


> > In firefox cards title goes on newline : ![image](https://user-images.githubusercontent.com/19426449/228214908-f7146aa5-1267-446c-bb3d-ec35ed6d1bcf.png)
> 
> @quinarygio Hmm, that is weird! At mine, it just looks normal in firefox. Don't know if this is really a problem? Or can we just leave it for what it is?
> 
> <img alt="Firefox geomap popup" width="369" src="https://user-images.githubusercontent.com/91895080/228235618-65e1beba-e207-4920-ae05-d8266f975494.png">

The problem occurs only when there is the scrollbar

2023-03-30 10:49 UTC, quinarygio commented
> > @quinarygio Even with the scrollbar I don't get the issue. Also in Edge and Chrome it works normal. So, I have no clue what it could be. Do you want me to find a solution for it?
> 
> Lets wait for a second check by @freddidierRTE to see if it could be reproduced or if it's just me..

I will merge it as nobody else reproduced the issue

2023-03-30 10:49 UTC, merged