First implementation opfab API
opfab/operatorfabric-core pull request #4567
Opened 2023-06-05 09:20 UTC by freddidierRTE

- In release note :
  -  In chapter :  Features 
  -  Text : #4438 Opfab API V1

2023-06-06 15:03 UTC, quinarygio requested changes

2023-06-08 12:24 UTC, vlo-rte requested changes

2023-06-08 12:24 UTC, vlo-rte commented on src/docs/asciidoc/reference_doc/ui_api.adoc
> +=== Function registerGetUserResponse
registerFunctionToGetUserResponse

2023-06-08 12:24 UTC, vlo-rte commented on src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
> +|opfab.currentCard.isLocked()
isResponseLocked

2023-06-08 12:24 UTC, vlo-rte commented on src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
> +|opfab.currentCard.listenToAnswerUnlock( ()  => {//do some stuff} )
listenToResponseUnlock

2023-06-08 12:24 UTC, vlo-rte commented on src/docs/asciidoc/resources/migration_guide_to_4.0.adoc
> +|opfab.currentCard.registerGetUserResponse( ()  => {//do some stuff} )
registerFunctionToGetUserResponse

2023-06-08 12:24 UTC, vlo-rte commented on src/test/api/karate/businessconfig/resources/bundle_test_action/template/template1.handlebars
> +  opfab.currentCard.registerGetUserResponse(() => {
registerFunctionToGetUserResponse

2023-06-08 12:24 UTC, vlo-rte commented on src/test/resources/bundles/messageOrQuestionExample/template/confirmation.handlebars
> +            opfab.currentCard.registerGetUserResponse(() => {
registerFunctionToGetUserResponse

2023-06-08 12:24 UTC, vlo-rte commented on ui/main/src/app/business/services/opfabAPI.service.ts
> +        opfab.currentCard.isLocked = function () {
isResponseLocked

2023-06-08 12:24 UTC, vlo-rte commented on ui/main/src/assets/js/templateGateway.js
> +            ' WARNING : Use of templateGateway.isLocked is deprecated , you shall use opfab.currentCard.isLocked() instead'
isResponseLocked

2023-06-08 12:24 UTC, vlo-rte commented on ui/main/src/assets/js/templateGateway.js
> +        opfab.currentCard.listenToAnswerLock(value);
listenToResponseLock

2023-06-08 12:24 UTC, vlo-rte commented on ui/main/src/assets/js/templateGateway.js
> +        opfab.currentCard.listenToAnswerUnlock(value);
listenToResponseUnlock

2023-06-08 12:24 UTC, vlo-rte commented on ui/main/src/assets/js/templateGateway.js
> +        opfab.currentCard.registerGetUserResponse(value);
registerFunctionToGetUserResponse

2023-06-12 08:55 UTC, ClementBouvierN commented on src/docs/asciidoc/reference_doc/ui_api.adoc
> +The frontend API is aimed to provide a way for template to communicate with the core opfab code. It's divided as follow :
"is aimed to " -> "is intended to" / "is aiming to"

2023-06-12 08:56 UTC, ClementBouvierN commented on src/docs/asciidoc/reference_doc/ui_api.adoc
> +- 'entityAllowedToSendCard' : boolean indicating whether the entity is allowed to send card or not
" to send card" -> "to send a card" / "to send cards"

2023-06-12 08:59 UTC, ClementBouvierN commented on src/docs/asciidoc/reference_doc/ui_api.adoc
> +It is also possible to append url extension (sub paths and/or parameters) to the url that will be called:
" append url extension" -> "append a url extension"

2023-06-12 09:03 UTC, ClementBouvierN commented on src/docs/asciidoc/reference_doc/ui_api.adoc
> +To adapt the template content to the display context it is possible to get from OperatorFabric the page context where the template will be rendered by calling the javascript function getDisplayContex
the page context -> the page's context

2023-06-12 09:20 UTC, ClementBouvierN commented on src/docs/asciidoc/reference_doc/ui_api.adoc
> +Card template can be informed when switching day/night mode by registering a listener  as follow :
" a listener  as " -> 2 spaces between listener and as

2023-06-12 09:23 UTC, ClementBouvierN commented on src/docs/asciidoc/reference_doc/ui_api.adoc
> +        opfab.currentCard.registerFunctionToGetUserResponse
no explanations ?

2023-06-13 10:24 UTC, vlo-rte approved these changes

2023-06-13 10:25 UTC, merged