Avoid utilities being dependent of services
opfab/operatorfabric-core pull request #4631
Opened 2023-06-19 14:27 UTC by freddidierRTE

Nothing in release note

2023-06-27 13:23 UTC, quinarygio requested changes

2023-06-27 13:23 UTC, quinarygio commented on ui/main/src/app/modules/useractionlogs/components/useractionlogs-table/cell-renderers/entities-cell-renderer.component.ts
Fix copyright

2023-06-27 13:23 UTC, quinarygio commented on ui/main/src/tests/mocks/entities.service.mock.ts
>   */
Fix Copyright

2023-06-28 06:52 UTC, freddidierRTE commented on ui/main/src/app/modules/useractionlogs/components/useractionlogs-table/cell-renderers/entities-cell-renderer.component.ts
ok

2023-06-28 12:45 UTC, merged