[OC-1025] : complete users admin module
opfab/operatorfabric-core pull request #467
Opened 2020-09-10 15:58 UTC by bendaoudmba

add to release notes:

[OC-1025]: new administration module for users, entities and groups management

2020-09-11 12:04 UTC, freddidierRTE commented
- For UsersController.java , use UserServiceImp as for other controller ? 
- Sonar issues : https://sonarcloud.io/project/issues?branch=OC-1025&id=org.lfenergy.operatorfabric%3Aoperatorfabric-core&resolved=false&types=CODE_SMELL 
- First , Previous , Next / Last , Filter by ..  are not traduce
- When you switch to french , traduction works but when you make a reload , traduction is again in english

2020-09-11 12:04 UTC, freddidierRTE requested changes

2020-09-14 10:19 UTC, bendaoudmba commented on ui/main/src/app/modules/admin/services/login-validator.service.ts
> +        }
use of promise.resolve method is necessary

2020-09-18 09:23 UTC, bendaoudmba commented on ui/main/src/app/modules/admin/admin-rooting.module.ts
> +export class AdminRoutingModule { }
for the moment, we have only /admin==>AdminComponent, but the module should evolve to have more rooting rule in the future

2020-09-18 09:23 UTC, bendaoudmba commented on ui/main/src/app/services/user.service.ts
> +  constructor(private httpClient: HttpClient, private groupsService: GroupsService) {
done

2020-09-18 12:31 UTC, bendaoudmba commented on ui/main/package.json
> +    "ngx-bootstrap": "^5.6.1",
ngx-bootstrap is required for pagination use, i uninstall ng-bootstra instead, and apparently, there is no regression

2020-09-29 13:04 UTC, freddidierRTE requested changes

2020-09-29 13:04 UTC, freddidierRTE commented on ui/main/src/app/modules/admin/components/ngtable/users/ofuserstable.component.ts
> +      console.log(locale);
remove this log

2020-09-29 13:04 UTC, freddidierRTE commented on ui/main/src/app/modules/admin/components/ngtable/users/ofuserstable.component.ts
> +          console.log(this.translate.currentLang);
remove this log

2020-09-29 13:04 UTC, freddidierRTE commented on ui/main/src/app/services/user.service.ts
> +            console.log(this._userWithPerimeters);
Remove this log

2020-09-29 13:04 UTC, freddidierRTE commented on ui/main/src/app/modules/admin/components/ngtable/users/ofuserstable.component.ts
> +    }).catch(() => console.log('error)'));
add error information in this log

2020-09-29 13:06 UTC, freddidierRTE commented
Bug : when creating a user with a space at the end , it create its but it is not possible to delete it after 
Solution --> remove space at the end of the  user login when saving 

+ resolve conflict

2020-09-29 13:11 UTC, bendaoudmba commented
well done , i will treat those points this afternoon

2020-09-29 15:50 UTC, bendaoudmba commented on ui/main/src/app/components/navbar/navbar.component.ts
> +    this.displayAdmin = this.userService.isCurrentUserAdmin() && this.configService.getConfigValue('admin.hidden');
done

2020-09-29 15:52 UTC, bendaoudmba commented on ui/main/src/app/modules/admin/components/ngtable/users/ofuserstable.component.ts
> +      console.log(locale);
done

2020-09-29 15:53 UTC, bendaoudmba commented on ui/main/src/app/modules/admin/components/ngtable/users/ofuserstable.component.ts
> +          console.log(this.translate.currentLang);
done

2020-09-29 15:53 UTC, bendaoudmba commented on ui/main/src/app/services/user.service.ts
> +            console.log(this._userWithPerimeters);
done

2020-10-02 08:03 UTC, merged