Simplify opfab configuration
opfab/operatorfabric-core pull request #4687
Opened 2023-07-05 06:33 UTC by freddidierRTE

- In release note :
  -  In chapter : Tasks
  -  Text : #Simplify configuration

2023-07-10 10:28 UTC, quinarygio requested changes

2023-07-10 10:28 UTC, quinarygio commented on config/dev/businessconfig-dev.yml
> +# This file contains only parameters that needs to be override compare to docker configuration
to be overridden
or
to be overwritten

2023-07-10 10:28 UTC, quinarygio commented on config/dev/cards-consultation-dev.yml
> +# This file contains only parameters that needs to be override compare to docker configuration
same as before

2023-07-10 10:28 UTC, quinarygio commented on config/dev/cards-publication-dev.yml
> +# This file contains only parameters that needs to be override compare to docker configuration
same as before

2023-07-10 10:28 UTC, quinarygio commented on config/dev/common-dev.yml
> +# This file contains only parameters that needs to be override compare to docker configuration
same as before

2023-07-10 14:41 UTC, vlo-rte commented on config/dev/cards-publication-dev.yml
> +# This file contains only parameters that needs to be override compare to docker configuration
that needs => that need
compare to docker configuration => from the docker configuration

2023-07-10 14:41 UTC, vlo-rte commented on config/dev/common-dev.yml
> +# This file contains only parameters that needs to be override compare to docker configuration
that needs => that need
compare to docker configuration => from the docker configuration

2023-07-10 14:41 UTC, vlo-rte commented on src/docs/asciidoc/deployment/configuration/configuration.adoc
> +|operatorfabric.servicesUrls.users|users:2103|Indicates where the Users service can be reached form the other services.
form => from

2023-07-10 14:41 UTC, vlo-rte commented on src/docs/asciidoc/deployment/configuration/configuration.adoc
> +|operatorfabric.servicesUrls.businessconfig|businessconfig:2100|Indicates where the Business service can be reached form the other services.
form => from

2023-07-10 14:41 UTC, vlo-rte commented on src/docs/asciidoc/deployment/configuration/configuration.adoc
> +|cardsReminder.checkPeriodInSeconds|||Cards remonder time interval between consecutive checks
remonder => reminder

2023-07-10 14:41 UTC, vlo-rte commented on src/docs/asciidoc/deployment/configuration/configuration.adoc
> +|checkIfUserIsAlreadyConnected|true|If false, OperatorFabric will allow a user to have several sessions opened at the same time. However, it may cause synchronization problems between the sessions us
let it to true => let it true

2023-07-10 14:42 UTC, vlo-rte requested changes
See my comments please.

2023-07-12 07:24 UTC, vlo-rte approved these changes

2023-07-12 07:24 UTC, merged