OC-1073 Kafka support
opfab/operatorfabric-core pull request #561
Opened 2020-11-02 18:57 UTC by JeroenGommans

Feature:
[OC-1073] Added initial Kafka support
Support to receive cards via Kafka topics. Added
- AVRO schema
- Kafka configuration options
- Kafka consumers
- Topic deserializer
- Documentation

2020-11-04 09:11 UTC, freddidierRTE requested changes
- Provide only one way of configuration via yml file (and not env file ) 
- Rebase or merge with  last develop version to have the new cards optional fields parentCardId & initialParentCardUid
- Some deprecated to solve if possible : 

_Task :client:cards-client-data:generateAvroJava
configuration key 'resource.loader' has been deprecated in favor of 'resource.loaders'
configuration key 'class.resource.loader.class' has been deprecated in favor of 'resource.loader.class.class'
configuration key 'file.resource.loader.class' has been deprecated in favor of 'resource.loader.file.class'
..._

2020-11-05 12:58 UTC, JeroenGommans commented on client/cards/src/main/avro/detail.avsc
> +      "default": null
I have removed fhem from the avro files.

2020-11-05 12:59 UTC, JeroenGommans commented on client/cards/src/main/avro/card.avsc
> +      "name": "parentCardUid",
Done. Merged and updated the said fields.

2020-11-05 13:00 UTC, JeroenGommans commented on client/cards/src/main/avro/card.avsc
> +      "default": null
I thought it might be used by the response cards. hence left it in the AVRO schema. I now removed the entry.

2020-11-05 13:02 UTC, JeroenGommans commented on config/docker/kafka-env.properties
> +#SPRING_DESERIALIZER_VALUE_DELEGATE_CLASS=org.lfenergy.operatorfabric.cards.publication.kafka.consumer.KafkaAvroWithoutRegistryDeserializer
Understood. I removed the properties file and the pointer to it from the cards-publication-docker.yml.
The idea was to have some kind of configuration outside of the docker .yml files. 
We now edit the .yml files to suit our environment, but we rather not edit them as we might accidentally check them in.

2020-11-05 13:02 UTC, JeroenGommans commented on services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/autoconfigure/kafka/ConsumerFactoryAutoConfiguration.java
> +package org.lfenergy.operatorfabric.autoconfigure.kafka;
Check!

2020-11-05 13:02 UTC, JeroenGommans commented on services/core/cards-publication/src/main/java/org/lfenergy/operatorfabric/autoconfigure/kafka/KafkaListenerContainerFactoryConfiguration.java
> +package org.lfenergy.operatorfabric.autoconfigure.kafka;
Check!

2020-11-06 08:38 UTC, freddidierRTE commented
Before i can merge your PR , could you please  modify the documentation to reflect last change : remove reference to kafka-env.properties file

2020-11-06 14:13 UTC, JeroenGommans commented
> Before i can merge your PR , could you please modify the documentation to reflect last change : remove reference to kafka-env.properties file

Ah. Good find!
I forgot to update the documentation. Fixed.

2020-11-09 09:32 UTC, merged