Do not mock opfab API anymore as it erases method that can be used in future unit test
opfab/operatorfabric-core pull request #6422
Opened 2024-05-03 14:37 UTC by freddidierRTE

2024-05-06 10:16 UTC, quinarygio requested changes

2024-05-06 10:16 UTC, quinarygio commented on ui/main/src/app/business/buildInTemplates/message-or-question-list/card/message-or-question-listCardTemplateView.spec.ts
> +        OpfabAPIService.currentCard.isUserAllowedToRespond = true;
should be isUserAllowedToRespond = false; ?
Anyway the test always pass, so it does not work well.
I think you must also set: 
 OpfabAPIService.currentCard.card = {data: {question: true}};

2024-05-06 15:26 UTC, freddidierRTE commented on ui/main/src/app/business/buildInTemplates/message-or-question-list/card/message-or-question-listCardTemplateView.spec.ts
> +        OpfabAPIService.currentCard.isUserAllowedToRespond = true;
Yes, you are right

2024-05-07 08:23 UTC, quinarygio approved these changes

2024-05-07 08:23 UTC, merged