In built-in question usercard add option to keep response history (#6670)
opfab/operatorfabric-core pull request #6755
Opened 2024-07-09 15:45 UTC by quinarygio

Fix #6670

- In release note :
  -  In chapter :  Features
  -  Text : #6670 : In built-in question usercard add option to keep response history

2024-07-10 15:43 UTC, freddidierRTE requested changes

2024-07-10 15:43 UTC, freddidierRTE commented on ui/main/src/app/business/builtInTemplates/question/card/questionCardTemplate.ts
> +                    html += ' </tr>';
It would be better to have the logic as much as possible in the view so put in the response object the already formatted field : entityName, responseDate 

And add a test in questionCardTemplateView.spec.ts to check responseDate and entityDate

2024-07-10 15:43 UTC, freddidierRTE commented on ui/main/src/app/business/builtInTemplates/question/card/questionCardTemplate.ts
> +                        html += '<td>' + resp.response + '</td> </tr>';
I think the resp.response field need to be escape (as it could contains malicious code)

2024-07-10 15:44 UTC, freddidierRTE commented
![image](https://github.com/opfab/operatorfabric-core/assets/58251627/d06bb415-13aa-42b2-92e3-c1677ab256a9)

If we have space or not in the text response we may have a "tab" inserted

2024-07-11 14:50 UTC, quinarygio commented
> ![image](https://private-user-images.githubusercontent.com/58251627/347473004-d06bb415-13aa-42b2-92e3-c1677ab256a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDk2NTksIm5iZiI6MTcyMDcwOTM1OSwicGF0aCI6Ii81ODI1MTYyNy8zNDc0NzMwMDQtZDA2YmI0MTUtMTNhYS00MmIyLTkyZTMtYzE2NzdhYjI1NmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDE0NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZWM5YmM5M2NkZDA4NzliYzZjN2VkNDM4N2I1NjdjM2E4ZWZiNDQ4ODQxMWJjNzM2ZTI1NDViM2U2ODRiZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CmWB4OGDvidM3TE6OEnJbKWW-L3M0Ok9ebQZqOXOsws)
> 
> If we have space or not in the text response we may have a "tab" inserted

I was not able to reproduce it

2024-07-12 15:13 UTC, freddidierRTE commented
i still reproduce non alignment in the table , as you do not reproduce it i try to solve it on my computer .

Adding `style="width:150px"`  it the "td" of the response date solve the problem  : 

![image](https://github.com/user-attachments/assets/78fda4be-92dd-41ab-b593-6068a705970c)

2024-07-12 15:17 UTC, freddidierRTE commented
Trying to solve the alignment pb , i saw that the date was saved as formatted text in the data of the child card . Could you store it as an epoch date . (This is to be consistent with all storage of dates) 

Sorry for this late review remark

2024-07-15 06:32 UTC, freddidierRTE approved these changes

2024-07-15 06:32 UTC, merged