Add card publisher entity in email body (#6926)
opfab/operatorfabric-core pull request #7012
Opened 2024-08-09 13:57 UTC by quinarygio

Fix #6926

- In release note :
  -  In chapter :  Features
  -  Text : #6926: Add card publisher entity in email body (

2024-08-26 14:25 UTC, freddidierRTE requested changes

2024-08-26 14:25 UTC, freddidierRTE commented on node-services/cards-external-diffusion/src/domain/server-side/BusinessConfigOpfabServicesInterface.ts
> +            this.clearBusinessConfigCache();
should be this.clearEntitiesCache()

2024-08-26 14:25 UTC, freddidierRTE commented on node-services/cards-external-diffusion/src/domain/server-side/BusinessConfigOpfabServicesInterface.ts
> +    private static readonly entitiesCache = new Map<string, any>();
The name of this class (BusinessConfigOpfabServicesInterface)  is confusing as this class is not only dealing with businessconfig but also with user information with this PR . So i propose to rename it cardsExternalDiffusionOpfabServicesInterface.ts (like it is named for reminder service)

2024-08-26 16:40 UTC, quinarygio commented on node-services/cards-external-diffusion/src/domain/server-side/BusinessConfigOpfabServicesInterface.ts
> +    private static readonly entitiesCache = new Map<string, any>();
As there is already a CardsExternalDiffusionOpfabServicesInterface class we could just move the functionalities of BusinessConfigOpfabServicesInterface into it ?

2024-08-28 12:05 UTC, freddidierRTE approved these changes

2024-08-28 12:05 UTC, merged