Add a cypress test for monitoring process to check columns when user select process (#6760)
opfab/operatorfabric-core pull request #7040
Opened 2024-08-16 10:29 UTC by vlo-rte

Nothing in release notes.

2024-08-19 15:42 UTC, quinarygio requested changes

2024-08-19 15:42 UTC, quinarygio commented on src/test/cypress/cypress/integration/MonitoringProcessus.spec.js
> +        //archivesAndLogging.unselectAllProcesses();
Commented code to be removed

2024-08-19 15:48 UTC, vlo-rte commented on src/test/cypress/cypress/integration/MonitoringProcessus.spec.js
> +        //archivesAndLogging.unselectAllProcesses();
Done.

2024-08-20 07:54 UTC, quinarygio approved these changes

2024-08-20 07:55 UTC, merged