Add user settings for showing acknowledgment footer in card details (#7360)
opfab/operatorfabric-core pull request #7381
Opened 2024-10-16 15:13 UTC by quinarygio

Fix #7360

- In release notes :
  -  In chapter : Features
  -  Text : #7360 :  Add user settings for showing acknowledgment footer in card details

2024-10-17 08:05 UTC, freddidierRTE commented on ui/main/src/app/business/services/user-permissions.service.ts
>      }
As this method is only used by card-body.view i would prefer having it directly in card-body.view

2024-10-17 08:05 UTC, freddidierRTE commented on ui/main/src/app/business/view/card/card-body.view.spec.ts
> +    it('GIVEN a card published by another entity WHEN process.state.showAcknowledgementFooter == ONLY_FOR_USERS_ALLOWED_TO_EDIT AND settings.showAcknowledgementFooter is false THEN acknowledgement fo
Introduce a test having a card published by another entity but a user member of an entity allowed to edit  (field entitiesAllowedToEdit in card)

2024-10-17 08:05 UTC, freddidierRTE commented on ui/main/src/app/modules/card/components/card-body/card-body.component.ts
> +        return this.cardBodyView.isCardAcknowledgedFooterVisible();
It is not stricly related to the PR but to avoid too much processing could you replace this method with a "compute"  method like for example computeShowDetailCardHeader()

2024-10-17 08:05 UTC, freddidierRTE commented on ui/main/src/app/modules/settings/components/settings/settings.component.ts
> +            'showAcknowledgementFooter',
OK @quinarygio  could you take it into account ?

2024-10-17 13:35 UTC, freddidierRTE requested changes

2024-10-17 13:35 UTC, freddidierRTE commented on ui/main/src/app/business/view/card/card-body.view.spec.ts
> +    it('GIVEN a card published by another entity WHEN process.state.showAcknowledgmentFooter == ONLY_FOR_USERS_ALLOWED_TO_EDIT AND settings.showAcknowledgmentFooter is false THEN acknowledgement foot
for state field , we keep  the old typo  : process.state.showAcknowledg**e**mentFooter

2024-10-17 13:35 UTC, freddidierRTE commented on ui/main/src/app/business/view/card/card-body.view.spec.ts
> +    it('GIVEN a card published by another entity WHEN process.state.showAcknowledgmentFooter = ONLY_FOR_USERS_ALLOWED_TO_EDIT and settings.showAcknowledgmentFooter is true THEN acknowledgement footer
for state field , we keep the old typo : process.state.showAcknowledgementFooter

2024-10-17 13:35 UTC, freddidierRTE commented on ui/main/src/app/business/view/card/card-body.view.spec.ts
> +    it('GIVEN a card publishe by another entity WHEN process.state.showAcknowledgmentFooter == FOR_ALL_USERS AND settings.showAcknowledgmentFooter is false THEN acknowledgement footer is shown', asyn
for state field , we keep the old typo : process.state.showAcknowledgementFooter

2024-10-17 13:35 UTC, freddidierRTE commented on ui/main/src/app/business/view/card/card-body.view.spec.ts
> +    it('GIVEN a card published by another entity WHEN process.state.showAcknowledgmentFooter == FOR_ALL_USERS and settings.showAcknowledgmentFooter is true THEN acknowledgement footer is shown', asyn
for state field , we keep the old typo : process.state.showAcknowledgementFooter

2024-10-17 13:35 UTC, freddidierRTE commented on ui/main/src/app/business/view/card/card-body.view.spec.ts
> +    it('GIVEN a card published by another entity WHEN process.state.showAcknowledgmentFooter == ONLY_FOR_USERS_ALLOWED_TO_EDIT AND user part of entities allowed to edit THEN acknowledgement footer is
for state field , we keep the old typo : process.state.showAcknowledgementFooter

2024-10-17 13:35 UTC, freddidierRTE commented on ui/main/src/app/business/view/card/card-body.view.spec.ts
> +    it('GIVEN a card published by an entity WHEN process.state.showAcknowledgmentFooter == NEVER AND  settings.showAcknowledgmentFooter is true THEN acknowledgement footer is not shown', async () =>
for state field , we keep the old typo : process.state.showAcknowledgementFooter

2024-10-17 13:35 UTC, freddidierRTE commented on ui/main/src/app/business/view/card/card-body.view.ts
> +    }
@quinarygio : to take into account

2024-10-17 13:35 UTC, freddidierRTE commented on ui/main/src/app/business/view/card/card-body.view.spec.ts
> +    it('GIVEN a card published by another entity WHEN process.state.showAcknowledgementFooter == ONLY_FOR_USERS_ALLOWED_TO_EDIT AND settings.showAcknowledgementFooter is false THEN acknowledgement fo
@quinarygio : i do not see , you took into account this remark ?

2024-10-17 13:37 UTC, freddidierRTE commented
Sonar issue : https://sonarcloud.io/project/issues?id=org.lfenergy.operatorfabric%3Aoperatorfabric-core&pullRequest=7381&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true

2024-10-17 14:10 UTC, quinarygio commented on ui/main/src/app/business/view/card/card-body.view.spec.ts
> +    it('GIVEN a card published by another entity WHEN process.state.showAcknowledgementFooter == ONLY_FOR_USERS_ALLOWED_TO_EDIT AND settings.showAcknowledgementFooter is false THEN acknowledgement fo
Yes:

    it('GIVEN a card published by another entity WHEN process.state.showAcknowledgementFooter == ONLY_FOR_USERS_ALLOWED_TO_EDIT AND user part of entities allowed to edit THEN acknowledgement footer is shown', async () => {
        const userWithPerimeters = getUserWithPerimeters(['ENTITY2']);

        configServerMock.setResponseForWebUIConfiguration(new ServerResponse({}, ServerResponseStatus.OK, null));
        await firstValueFrom(ConfigService.loadWebUIConfiguration());

        ConfigService.setConfigValue('settings.showAcknowledgmentFooter', false);
        card = getOneCard({
            publisher: 'ENTITY1',
            publisherType: 'ENTITY',
            process: 'testProcess',
            processVersion: '1',
            state: 'state3',
            entityRecipients: ['ENTITY1', 'ENTITY2', 'ENTITY_FR'],
            entitiesAllowedToEdit: ['ENTITY2']
        });
        cardBodyView = new CardBodyView(card, userWithPerimeters);

        expect(cardBodyView.isCardAcknowledgedFooterVisible()).toBeTrue();
    });

2024-10-18 05:51 UTC, freddidierRTE approved these changes

2024-10-18 05:51 UTC, merged