Homogenize number of lines for table multiselect position (#7761)
opfab/operatorfabric-core pull request #7771
Opened 2024-12-27 17:46 UTC by vlo-rte

- In release notes :
  -  In chapter : Features Bugs Tasks
  -  Text : #xxx ...

2025-01-06 08:28 UTC, freddidierRTE commented
Small vertical unalignment between line per page and pagination and more space between "page"  and "Results"
![image](https://github.com/user-attachments/assets/91aaaece-d20d-4f7f-95cc-0c2c6148e6b3)

Avoid new line when zooming if possible :

![image](https://github.com/user-attachments/assets/4e376668-9b8f-4b89-bf10-1606a6131993)

2025-01-06 08:29 UTC, freddidierRTE requested changes

2025-01-06 08:29 UTC, freddidierRTE commented on ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
> +    }
instead of getting the element via his id , you can take it via the method param , suggestion not tested : 

```
onPageSizeChange(element) {
const value = element.value; 
...
}

2025-01-06 08:31 UTC, vlo-rte commented
> Small vertical unalignment between line per page and pagination and more space between "page" and "Results" ![image](https://private-user-images.githubusercontent.com/58251627/400350291-91aaaece-d20d-4f7f-95cc-0c2c6148e6b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTI1MDIsIm5iZiI6MTczNjE1MjIwMiwicGF0aCI6Ii81ODI1MTYyNy80MDAzNTAyOTEtOTFhYWFlY2UtZDIwZC00ZjdmLTk1Y2MtMGMyYzYxNDhlNmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDA4MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MTdiMzIwOGE0Y2E0ZWFmM2NlNTc2OWYxNTRkYzdiOTA5MjdlMDJiYzU4NGMzOTdjMGNmMDk2N2IyODI4MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aQjU9hs6X8mgNu6XPP2qZT0ZNx5QovAktL_kSjNf9Ok)
> 
> Avoid new line when zooming if possible :
> 
> ![image](https://private-user-images.githubusercontent.com/58251627/400354064-4e376668-9b8f-4b89-bf10-1606a6131993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTI1MDIsIm5iZiI6MTczNjE1MjIwMiwicGF0aCI6Ii81ODI1MTYyNy80MDAzNTQwNjQtNGUzNzY2NjgtOWI4Zi00Yjg5LWJmMTAtMTYwNmE2MTMxOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDA4MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MjM4ZDg5ZDA2MzBiNzU4MTE2M2EwMWQ3NWY1ZGNlMWYwMGI3NjNjYmViNTQ0ZDliZTBjMDk1Y2ViN2QzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6dMzEm7H7kVcWgDdekQ5WxxLIFtSmrR1VbYUSgRaGe0)

I didn't have this result. What browser do you use ?

2025-01-06 10:56 UTC, vlo-rte commented on ui/main/src/app/modules/admin/components/table/admin-table.directive.ts
> +    }
Done.

2025-01-06 10:56 UTC, vlo-rte commented
> > Small vertical unalignment between line per page and pagination and more space between "page" and "Results" ![image](https://private-user-images.githubusercontent.com/58251627/400350291-91aaaece-d20d-4f7f-95cc-0c2c6148e6b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTI1MDIsIm5iZiI6MTczNjE1MjIwMiwicGF0aCI6Ii81ODI1MTYyNy80MDAzNTAyOTEtOTFhYWFlY2UtZDIwZC00ZjdmLTk1Y2MtMGMyYzYxNDhlNmIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDA4MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MTdiMzIwOGE0Y2E0ZWFmM2NlNTc2OWYxNTRkYzdiOTA5MjdlMDJiYzU4NGMzOTdjMGNmMDk2N2IyODI4MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aQjU9hs6X8mgNu6XPP2qZT0ZNx5QovAktL_kSjNf9Ok)
> 
> I didn't have this result. What browser do you use ?
> 
> > Avoid new line when zooming if possible :
> > ![image](https://private-user-images.githubusercontent.com/58251627/400354064-4e376668-9b8f-4b89-bf10-1606a6131993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxNTI1MDIsIm5iZiI6MTczNjE1MjIwMiwicGF0aCI6Ii81ODI1MTYyNy80MDAzNTQwNjQtNGUzNzY2NjgtOWI4Zi00Yjg5LWJmMTAtMTYwNmE2MTMxOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDA4MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MjM4ZDg5ZDA2MzBiNzU4MTE2M2EwMWQ3NWY1ZGNlMWYwMGI3NjNjYmViNTQ0ZDliZTBjMDk1Y2ViN2QzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6dMzEm7H7kVcWgDdekQ5WxxLIFtSmrR1VbYUSgRaGe0)

Done.

2025-01-07 11:20 UTC, freddidierRTE approved these changes

2025-01-07 11:20 UTC, merged