[OC-1257] Set groups of entities compatible with reponse card
opfab/operatorfabric-core pull request #821
Opened 2021-03-04 10:22 UTC by quinarygio

Release notes:

In Features:
[OC-1257] Set groups of entities compatible with response card. Added "entityAllowedToSendCard "boolean field to Entity.
NOTE: If an Entity has entityAllowedToSendCard=false and has child entities, than child entities will be checked recursively

2021-03-04 15:29 UTC, freddidierRTE commented on ui/main/src/app/services/entities.service.ts
> +        console.log("Foreach entity " + entity.id);
remove console.log

2021-03-04 15:29 UTC, freddidierRTE commented on ui/main/src/app/services/entities.service.ts
> +          console.log("Concat childs of entity " + entity.id + " size: " + childsAllowed.length);
remove console.log

2021-03-04 16:06 UTC, quinarygio commented on ui/main/src/app/services/entities.service.ts
> +          console.log("Concat childs of entity " + entity.id + " size: " + childsAllowed.length);
Done

2021-03-04 16:06 UTC, quinarygio commented on ui/main/src/app/services/entities.service.ts
> +        console.log("Foreach entity " + entity.id);
Done

2021-03-05 08:21 UTC, freddidierRTE requested changes
1) Add or modify a karate test to set/get the new field entityAllowedToSendCard

2) Add in documentation src/docs/asciidoc/reference_doc/users_management.adoc (chapter entities) 

3) Add a goup of entity in the standard conf to faciliate test : in config/dev/users-dev.yml and in config/docker/users-docker.yml
--> 

 ```
 entities:
    - id: ENTITY1
      name: Control Room 1
      description: Control Room 1
      parents : ["ALLCONTROLROOMS"]
    - id: ENTITY2
      name: Control Room 2
      description: Control Room 2
      parents : ["ALLCONTROLROOMS"]
    - id: ENTITY3
      name: Control Room 3
      description: Control Room 3
      parents : ["ALLCONTROLROOMS"]
    - id: ALLCONTROLROOMS
      name: All Control Rooms 
      description: All Control Rooms
      entityAllowedToSendCard: false
    - id: ENTITY4
      name: IT Supervision Center 
      description: IT Supervision Center 


```
4) WIth the previous config when sending usercard "Example for new cards 2 /  question" to ALLCONTROLROOMS , it is not possible to respond for operator2 --> it shall be possible 

5) WIth the previous config when sending usercard "Example for new cards 2 /  question" to ENTITY1 (controlroom1) and ENTITY2(controlroom2) , when responding with operator2 , the respond is made on behalf of entity ALLCONTROLROOMS instead of ENTITY2
![image](https://user-images.githubusercontent.com/58251627/110087474-00facb80-7d94-11eb-823a-8fea845c6533.png)

6) The list of answers in the card header should reflect the list of enitity Allowed to respond taking into account the entityAllowedToSendCard

![image](https://user-images.githubusercontent.com/58251627/110087891-82eaf480-7d94-11eb-8e30-70775e23eac1.png)

2021-03-09 09:39 UTC, quinarygio commented on ui/main/src/app/services/entities.service.spec.ts
> +
Done

2021-03-09 09:39 UTC, quinarygio commented on ui/main/src/app/services/entities.service.spec.ts
> +    it('should return an Entity[]', () => {
Done

2021-03-09 09:40 UTC, quinarygio commented on ui/main/src/app/modules/cards/components/detail/detail.component.ts
> +            const allowed = EntitiesService.getEntitiesAllowedToRespond(entitiesToRespond, this.entitiesService.getEntities()).map(entity => entity.id);
Done

2021-03-09 09:40 UTC, quinarygio commented on ui/main/src/app/services/entities.service.ts
> +          console.log("Get childs of entity " + entity.id);
Done

2021-03-10 09:43 UTC, merged