[OC-1538] BUG - FeedNotification configuration
opfab/operatorfabric-core pull request #842
Opened 2021-03-12 09:40 UTC by vlo-rte

Release notes : 

In bug section : 

[OC-1538](https://opfab.atlassian.net/browse/OC-1538) : BUG - FeedNotification configuration - processes not sorted by their label

2021-03-15 17:10 UTC, quinarygio requested changes

2021-03-15 17:10 UTC, quinarygio commented on ui/main/src/app/services/processes.service.ts
> +
Check that a processDefinition is found

2021-03-16 08:35 UTC, vlo-rte commented on ui/main/src/app/services/processes.service.ts
> +
Done.

2021-03-16 10:38 UTC, quinarygio approved these changes

2021-03-16 10:39 UTC, merged