[OC-1584] Usercard : permit to have a restricted list of recipient
opfab/operatorfabric-core pull request #963
Opened 2021-04-21 14:50 UTC by quinarygio

Release notes

In Tasks section:
[OC-1584] Usercard : permit to have a restricted list of recipients  depending on the state and process
Note: in bundle config.json added in state definition  a "recipientList" field to configure a list of entities and optionally the levels of connection of related childs to be included in recipient list. Level 0 meaning the entity itself, level 1 for first level childs, level 2 for 2nd level connections, etc.

2021-04-22 13:54 UTC, AlexGuironnetRTE requested changes
Hello,

Documentation is clear, I have a few remarks on the code (see comments), the given example works as intended but the following edge case doesn't:
This config: 
`
"recipientList" : [{"id": "ALLCONTROLROOMS", "levels": [1,0]}, {"id": "ENTITY4"}, {"id": "ENTITY2"}, {"id": "entityKarate1", "levels":  [1]}]`

yields

![image](https://user-images.githubusercontent.com/45459065/115726316-ea7bf400-a382-11eb-9ad4-941932c07b5e.png)

Control Room 2 is duplicated.

2021-04-22 13:54 UTC, AlexGuironnetRTE commented on ui/main/src/app/model/processes.model.ts
> +        readonly id?: string,
Is the id really meant to be optional ?

2021-04-22 13:54 UTC, AlexGuironnetRTE commented on services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCardData.java
> +import javax.validation.Valid;
```suggestion
```
Sonar says this import is not used.

2021-04-22 15:51 UTC, quinarygio commented on services/core/businessconfig/src/main/modeling/swagger.yaml
> +      with 0 meaning the entity itself, 1 for first level childs, 2 for 2nd level connections, etc.
Done

> Hello,
> 
> Documentation is clear, I have a few remarks on the code (see comments), the given example works as intended but the following edge case doesn't:
> This config:
> ` "recipientList" : [{"id": "ALLCONTROLROOMS", "levels": [1,0]}, {"id": "ENTITY4"}, {"id": "ENTITY2"}, {"id": "entityKarate1", "levels": [1]}]`
> 
> yields
> 
> ![image](https://user-images.githubusercontent.com/45459065/115726316-ea7bf400-a382-11eb-9ad4-941932c07b5e.png)
> 
> Control Room 2 is duplicated.

Fixed.

2021-04-22 15:51 UTC, quinarygio commented on src/docs/asciidoc/reference_doc/user_cards.adoc
> +      "recipientList" : [{"id": "ENTITY1", "levels": [0,1]}, {"id": "ENTITY4"}]
Done

2021-04-22 15:51 UTC, quinarygio commented on src/docs/asciidoc/reference_doc/user_cards.adoc
> +In this example the list of available recipients will contain: "ENTITY1" (level 0), all the first level childs of "ENTITY1" (level 1) and "ENTITY4".
Done

2021-04-22 15:51 UTC, quinarygio commented on src/docs/asciidoc/reference_doc/user_cards.adoc
> +      "recipientList" : [{"id": "ENTITY1", "levels": [0,1]}, {"id": "ENTITY4"}]
Done

2021-04-22 15:51 UTC, quinarygio commented on ui/main/src/app/model/processes.model.ts
> +        readonly id?: string,
You are right,.. Fixed

2021-04-22 15:51 UTC, quinarygio commented on services/core/businessconfig/src/main/java/org/opfab/businessconfig/model/UserCardData.java
> +import javax.validation.Valid;
Done

2021-04-26 13:23 UTC, AlexGuironnetRTE approved these changes
Changes and tests OK

2021-04-26 13:23 UTC, merged